#------------------------------------------------------------------------------#
# Code for "The value of environmental sampling surveillance"
# Copyright (C) 2024 by The RAND Corporation
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# See LICENSE.md and README.md for more information on usage and licensing
#
# Author: Pedro Nascimento de Lima
#------------------------------------------------------------------------------#

# Increase n_reps to 1,000 for a real-scale run.
# Only do that in a capable machines
# n_reps - use 1,000 for real runs, use 50 to just test the code.
n_reps_main: 1000

# This number of replications can be smaller since we don't report prediction intervals in-text; only in figures.
n_reps_tau: 100

# How many cores to use if running simulations in parallel
n_cores: 5

# Set random seed:
seed: 1234

# Whether to run simulations in parallel
parallel: TRUE

# If running model in parallel, create experiment from the cluster_eval file
model_from_cluster_eval: TRUE

# If model_from_cluster_eval is TRUE, this file must instiate a cluster_experiment object
# This object will be instantiated in each parallel process *once* before running all simualations
# This appears to be the only way to run the model in parallel with odin at the moment.
cluster_eval_script: "./R/scripts/cluster_eval.R"

# Use this file to set global project settings:
data_file: "./data/metapopulation-inputs-master.xlsx"

lib_path: "./R/functions"

# FALSE if loading from installed package
r6sim_load_all: FALSE

# Whether to use renv: only used when installing packages
use_renv: FALSE
